server:
  port: 9000
  
# 뷰 페이지
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource: # 마이바티스 dataSource객체 세팅
    driver-class-name: 
    url: jdbc:mysql://1.246.60.149:5000/soboon?characterEncoding=utf-8
    username: a3b3
    password: 1234
    
  devtools: # 코드 수정시 서버 자동 재시작
    livereload:
      enabled: true
    
  mail:
     host: smtp.gmail.com
     port: 587
     username: soboonsoboon@gmail.com
     password: gcelqqspqoeykrrv
     properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
mybatis:
  type-aliases-package: com.semiproject.soboon.vo
  mapper-locations: mapper/*Mapper.xml

  
  